platform :ios, '11.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorSecureStoragePlugin', :path => '../../node_modules/capacitor-secure-storage-plugin'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
  pod 'CordovaPluginsStatic', :path => '../capacitor-cordova-ios-plugins'
  # Do not delete
end

target 'Wantic' do
  pod 'GoogleUtilities', '~> 7.4'
  capacitor_pods
  # Add your Pods here
end

target 'Wantic Beta' do
  pod 'GoogleUtilities', '~> 7.4'
  capacitor_pods
  # Add your Pods here
end

def share_extension_pods
  pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '3.x'
  pod 'GoogleUtilities', '~> 7.4'
  pod 'Firebase/Analytics', '~> 8.2.0'
  pod 'Firebase/Auth', '~> 8.2.0'
end

target 'Share' do
  share_extension_pods
end

target 'Share Beta' do
  share_extension_pods
end